
#define PORT_WELCOME_SERVER 56700 /// INIZIALIZE THE WELCOME PORT OF THE SERVER

#define ADDRESS_SERVER "127.0.0.1" ///INIZIALIZE THE ADDRESS OF THE SERVER AND THE CLIENT

struct sockaddr_in sad; /// INIZIALIZATION OF THE STRUCT WHICH WILL CONTAIN THE INFORMATION OF THE SERVER

struct sockaddr_in cad; /// INIZIALIZATION OF THE STRUCT WHICH WILL CONTAIN THE INFORMATION OF THE SERVER

///INIZIALIZE THE STRUCT TO PASS THE OPERATION, NUMBER AND RESULT BETWEEN THE CLIENT AND SERVER

typedef struct  {
	char operation;
	long first_number;
	long second_number;
	float result;
} msgStruct;

#define NO_ERROR 0 /// INIZIALIZE VARIABLE TO CHECK FOR ERROR

struct hostent *host;
